spring.datasource.url=jdbc:postgresql://db:5432/enigma_db
spring.datasource.username=postgres
spring.datasource.password=enigma123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
server.port=8080