spring.datasource.url=jdbc:postgresql://db:5432/enigma_db
spring.datasource.username=postgres
spring.datasource.password=enigma123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
server.port=8080

# ==========================================
# ADMIN PANEL SECURITY
# SHA-256 hash of password: 4Dm!nGi@Hyu*(4S3
# Generated: echo -n '4Dm!nGi@Hyu*(4S3' | sha256sum
# ==========================================
admin.password.hash=e92a126170533ea44dd4033231b9150bce1fa4643d9c3b40a26ca0589a5d11a6
admin.session.cookie=enigma_admin_session
admin.session.duration.hours=8

# ==========================================
# KONFIGURACJA POCZTY E-MAIL (home.pl)
# ==========================================
spring.mail.host=poczta2646518.home.pl
spring.mail.port=465
spring.mail.username=wsproject@wsproject.pl
spring.mail.password=G@l3$zw!k
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtps.timeout=8000